# Generated by Django 6.0 on 2026-01-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Atena', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
            ],
        ),
    ]
