# Generated by Django 6.0 on 2026-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_organization_address_organization_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Logotipo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Atena', max_length=200, verbose_name='Nome da Organização'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SELLER', 'Vendedor')], default='SELLER', max_length=50, verbose_name='Cargo'),
        ),
    ]
