# Generated by Django 6.0 on 2026-01-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_supplier_product_service'),
        ('sales', '0002_remove_saleitem_item_saleitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
