# Generated by Django 6.0 on 2026-01-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=5, verbose_name='Estoque Mínimo'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilo'), ('L', 'Litro'), ('M', 'Metro')], default='UN', max_length=2, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
    ]
